"""
Phase 1: Basic LLM Chat API using LangChain (No RAG, No Embeddings, No Agents)

Goal:
User message -> Backend -> LangChain ChatOpenAI -> Response

This is the most minimal, educational implementation of an LLM chat endpoint using LangChain.
Everything is in this single file so you can easily understand the flow:
1. Load environment (.env)
2. Define Pydantic request/response schemas
3. Map messages to LangChain message classes (HumanMessage, AIMessage, SystemMessage)
4. Call LangChain's ChatOpenAI model asynchronously (ainvoke)
5. Extract reply and token usage metadata
"""

import os
from typing import List, Optional
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

# LangChain Imports
from langchain_openai import ChatOpenAI
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, SystemMessage

# -----------------------------------------------------------------------------
# 1. Environment & Configuration
# -----------------------------------------------------------------------------
load_dotenv()

API_KEY = os.getenv("OPENAI_API_KEY") or os.getenv("LLM_API_KEY")
BASE_URL = os.getenv("LLM_BASE_URL") or None  # Optional: for Groq, Ollama, DeepSeek, etc.
DEFAULT_MODEL = os.getenv("LLM_DEFAULT_MODEL", "gpt-4o-mini")

# -----------------------------------------------------------------------------
# 2. Request & Response Schemas (Pydantic)
# -----------------------------------------------------------------------------
class ChatMessage(BaseModel):
    """Represents a single message with a role ('user', 'assistant', or 'system')."""
    role: str = Field(default="user", description="Sender role: user, assistant, or system")
    content: str = Field(..., min_length=1, description="Text content of the message")


class ChatRequest(BaseModel):
    """Input payload sent by the user/client."""
    messages: List[ChatMessage] = Field(..., min_length=1, description="List of chat messages")
    model: Optional[str] = Field(None, description="Optional model override")
    temperature: Optional[float] = Field(0.7, ge=0.0, le=2.0, description="Creativity: 0.0 is strict, 1.0+ is creative")


class UsageInfo(BaseModel):
    """Token usage reported by the model."""
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0


class ChatResponse(BaseModel):
    """Output payload returned to the user/client."""
    reply: str
    model: str
    usage: UsageInfo


# -----------------------------------------------------------------------------
# 3. Helper: Convert to LangChain Messages
# -----------------------------------------------------------------------------
def to_langchain_message(msg: ChatMessage) -> BaseMessage:
    """
    LangChain uses distinct message classes instead of raw dictionaries:
    - HumanMessage: messages sent by the user
    - AIMessage: messages generated by the AI
    - SystemMessage: instructions directing model behavior
    """
    if msg.role == "system":
        return SystemMessage(content=msg.content)
    elif msg.role == "assistant":
        return AIMessage(content=msg.content)
    else:
        return HumanMessage(content=msg.content)


# -----------------------------------------------------------------------------
# 4. FastAPI Application & Chat Endpoint
# -----------------------------------------------------------------------------
app = FastAPI(
    title="MumtaAI - Phase 1 Basic Chat (LangChain)",
    description="Minimal LLM Chat API using LangChain without RAG.",
    version="1.0.0",
)


@app.get("/health")
async def health():
    """Simple health check endpoint."""
    return {"status": "healthy"}


@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest) -> ChatResponse:
    """
    Main Chat Endpoint using LangChain:
    Receives messages -> Converts to LangChain format -> Invokes ChatOpenAI -> Returns response.
    """
    if not API_KEY:
        raise HTTPException(
            status_code=500,
            detail="API Key is missing. Please set OPENAI_API_KEY in your .env file.",
        )

    try:
        # 1. Initialize LangChain's ChatOpenAI model
        llm = ChatOpenAI(
            api_key=API_KEY,
            base_url=BASE_URL,
            model=request.model or DEFAULT_MODEL,
            temperature=request.temperature,
        )

        # 2. Convert incoming messages to LangChain message objects
        langchain_messages = [to_langchain_message(m) for m in request.messages]

        # 3. Call the model asynchronously using .ainvoke()
        ai_response = await llm.ainvoke(langchain_messages)

        # 4. Extract token usage metadata from LangChain response
        prompt_tokens = 0
        completion_tokens = 0
        total_tokens = 0

        # LangChain standard usage metadata
        if hasattr(ai_response, "usage_metadata") and ai_response.usage_metadata:
            meta = ai_response.usage_metadata
            prompt_tokens = meta.get("input_tokens", 0)
            completion_tokens = meta.get("output_tokens", 0)
            total_tokens = meta.get("total_tokens", 0)
        elif hasattr(ai_response, "response_metadata"):
            token_usage = ai_response.response_metadata.get("token_usage", {})
            prompt_tokens = token_usage.get("prompt_tokens", 0)
            completion_tokens = token_usage.get("completion_tokens", 0)
            total_tokens = token_usage.get("total_tokens", 0)

        # Content can be a string or a list of parts in multimodal
        content = ai_response.content if isinstance(ai_response.content, str) else str(ai_response.content)

        return ChatResponse(
            reply=content,
            model=request.model or DEFAULT_MODEL,
            usage=UsageInfo(
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
                total_tokens=total_tokens,
            ),
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"LangChain Error: {str(e)}")


# -----------------------------------------------------------------------------
# 5. Local Development Server Runner
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    import uvicorn

    port = int(os.getenv("PORT", 8000))
    print(f"\n🚀 MumtaAI LangChain Chat Server running at http://localhost:{port}")
    print(f"📖 Interactive API Docs available at http://localhost:{port}/docs\n")
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=True)
